// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQMeTIbce9fXkb_oR_0jIssRhhBf1wRZ8',
    appId: '1:515211028276:web:3e53cb9fd09770ee592761',
    messagingSenderId: '515211028276',
    projectId: 'pgphs-reunion',
    authDomain: 'pgphs-reunion.firebaseapp.com',
    storageBucket: 'pgphs-reunion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7kMKvzLYf92wtvdplmAE50HVWOpjj7u4',
    appId: '1:515211028276:android:6a64490558c996a3592761',
    messagingSenderId: '515211028276',
    projectId: 'pgphs-reunion',
    storageBucket: 'pgphs-reunion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhg7Pfm2I8i45xW-7CJxPTrVUTtS6W-2w',
    appId: '1:515211028276:ios:a202dceb3d956d47592761',
    messagingSenderId: '515211028276',
    projectId: 'pgphs-reunion',
    storageBucket: 'pgphs-reunion.firebasestorage.app',
    iosBundleId: 'com.example.pgphsReunion',
  );
}
